language: perl
perl:
        - "5.24.1"
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
  - sudo apt-get -qq update
  - sudo apt-get install libpango-perl libpango1.0-dev libgtk2-perl libgtk2.0-bin libgtk2.0-dev libvte-dev libvte9 -y

script: prove -lr test.pl

install:
  - cpanm --quiet --installdeps --notest Gnome2::Vte
  - cpanm --quiet --installdeps --notest Devel::Cover
